### 
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "initiate",
    "name" : "ITEM1",
    "coordinate" : [2,2,2],
    "psswd": 12345
}

### 

POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "registrate",
    "name" : "ITEM1",
    "psswd": 12345
}

### 

POST http://0.0.0.0:6064/set_area HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "area" : [-1,-1,100,100]
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "start",
    "name" : "ITEM1",
    "speed" : 1,
    "psswd": 12345
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "stop",
    "name" : "ITEM1",
    "psswd": 12345
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "sign_out",
    "name" : "ITEM1",
    "psswd": 12345
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "move_to",
    "name" : "ITEM1",
    "coordinate" : [11,11,1],
    "speed" : 1,
    "psswd": 12345
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "new_task",
    "name" : "ITEM1",
    "points" : [[5,5,5,0],[8,8,8,1],[11,11,11,1],[16,16,11,0]],
    "psswd": 12345
}

###
POST http://0.0.0.0:6065/set_command HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "command" : "clear_flag",
    "name" : "ITEM1",
    "psswd": 12345
}

